version: "3"

services:
  front:
    build:
      context: .
      dockerfile: front.dockerfile
    container_name: front
    restart: always
    depends_on:
      - api
    ports:
      - "80:8080"

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: "api"
    #restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db